config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end
class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end
Timetracker::Application.routes.draw do
  # get 'users/index'

  # get 'projects/index'

  constraints(SubdomainPresent) do
    root 'projects#index',as: :subdomain_root
    devise_for :users
    resources :users,only: :index
  end
  constraints(SubdomainBlank) do
    root 'welcome#index'
    resources :accounts,only: [:new,:create]
  end
end 

app/models/account.rb
class Account < ActiveRecord::Base
  RESTRICTED_SUBDOMAINS= %w(wwww)
  validates :subdomain,presence:true,uniqueness: {case_sensitive: false},format: {with: /\A[\w\-]+\Z/i,message: 'contains invalid characters'},exclusion:{in: RESTRICTED_SUBDOMAINS,message: 'restricted'}
  before_validation :downcase_subdomain
  validates :owner,presence: true
  belongs_to :owner,:class_name=>"User"
  accepts_nested_attributes_for :owner
  private
  def downcase_subdomain
    self.subdomain = subdomain.try(:downcase)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable,
         :recoverable, :rememberable,  :validatable
  validates_presence_of :name
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  skip_before_filter :authenticate_user!,only: [:new,:create]

  def new
    @account= Account.new
    @account.build_owner
  end
  def create
    @account =Account.new(account_params)
    if @account.valid?
      Apartment::Database.create(@account.subdomain)
      Apartment::Database.switch(@account.subdomain)
      @account.save
      redirect_to new_user_session_url(subdomain: @account.subdomain)
    else
      render action: 'new'
    end
  end
  private
  def account_params
    params.require(:account).permit(:subdomain,owner_attributes:[:name,:email,:password,:password_confirmation])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :load_schema,:authenticate_user!,:set_mailer_host
  private
    def load_schema
    Apartment::Database.switch('public')
    return unless request.subdomain.present?

    if current_account
      Apartment::Database.switch(current_account.subdomain)
    else
      redirect_to root_url(subdomain: false)
    end
    end
    def current_account
      @current_account||= Account.find_by(subdomain: request.subdomain)
    end
    helper_method :current_account
    def set_mailer_host
      subdomain=current_account? "#{current_account.subdomain}." : ""
      ActionMailer::Base.default_url_options[:host]="#{subdomain}lvh.me:3000"
    end
  def after_sign_out_path_for(resource_or_scope)
   new_user_session_path
  end 
  def after_invite_path_for(resource)
    users_path
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
skip_before_filter :authenticate_user!,only: :index
  def index
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_status(user)
   if current_account.owner ==user
     content_tag(:span,'',class:'glyphicon glyphicon-ok color-success')
   else
     'Invitation Pending'
   end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accounts/new.html.erb
<div class="col-md-6 col-md-offset-3 panel panel-default">
<div class="panel-body">
<h2>Create an account</h2>
<%= form_for @account do |f|%>

  <div class="input-group">
    <%=f.label :subdomain%>
    <%=f.text_field :subdomain,class: "form-control"%>
    <span class="input-group-addon">.timetracker.dev</span>
  </div>
  <%=f.fields_for :owner do |o|%>
    <div class="input-group">
      <%=o.label :name%>
      <%=o.text_field :name,class: "form-control"%>
    </div>
    <div class="input-group">
      <%=o.label :email%>
      <%=o.text_field :email,class: "form-control"%>
    </div>
    <div class="input-group">
      <%=o.label :password%>
      <%=o.text_field :password,class: "form-control"%>
    </div>
    <div class="input-group">
      <%=o.label :password_confirmation%>
      <%=o.text_field :password_confirmation,class: "form-control"%>
    </div>
   <%end%>
  <%= f.submit%>
  <%end%>
  </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracker</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="container">
<nav class="navbar navbar-default">
<div class="navbar-header">
   <%= link_to 'Time Tracker',root_path ,class:'navbar-brand'%>
</div>
<div class="pull-right right-buttons">
<% if user_signed_in? %>
 <%= link_to('Logout', destroy_user_session_path, :method => :delete,class:'btn btn-default navbar-btn') %>
<% else %>
 <%= link_to('Login', new_user_session_path,class:'btn btn-default navbar-btn')  %> 
<% end %>
</div>
<ul class="nav navbar-nav navbar-right">
  <li> <%= link_to 'Users' ,users_path %></li>
</ul>
</nav>
</header>
<div class="container">
<% flash.each do |name,msg|%>
  <%= content_tag :div,msg,:id=>"flash#{name}"%>
<%end%>
<%#= flash_messages if show_layout_flash?%>
<div class="row">
<%= yield %>
</div>
</div>
</body>
</html>

app/views/projects/index.html.erb
<div class="col-md-12">
   <div class="well">Hello! You can now track time</div>
</div>

app/views/users/index.html.erb
<div class="col-md-8 col-md-offset-2">
<h2> Authorized Users</h2>
<div class='panel panel-default'>
   <div class="panel-body">
     <div class="table table-striped">
     <table>
        <thead>
          <th>Name</th>
          <th>Email </th>
          <th>Status</th>
        </thead>
        <tbody>
          <%@users.each do |user|%>
            <tr>
            <td><%=user.name%></td>
            <td><%=user.email%></td>
            <td><%=user_status(user)%></td>
            </tr>
          <%end%>
        </tbody>
     </table>
     </div>
   </div>
</div>
<h3 class="extra-margin-top"> Invite User</h3>
<%= simple_form_for(User.new,url: user_invitation_path,html:{class: 'form-inline'}) do |f| %>
  <%=f.input :email ,placeholder:'Email',label:false%>
  <%=f.button :submit ,'Invite User',class:'btn-primary'%>
<%end%>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<div class="col-md-12">
 <div class="jumbotron">
 <h1> Time Tracker</h1>
 <p> Track your time with the most awesome time tracking app ever </p>
<%= link_to "Create Account",new_account_path,class:'btn btn-primary btn-lg'%>
</div>
</div>